name: Continuous Integration
on: push
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    container:
      image: node:14.5.0-alpine
    services:
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: "prdetails"
            MYSQL_ROOT_PASSWORD: "Priyanka#123"
          ports:
            - 33306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test