name: Continuous Integration
on: push
jobs:
  run_code_checks:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'prdetails'
          mysql root password: 'Priyanka#123'
      - name: Run tests
        run: go test