name: Continuous Integration
on: push
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          mysql database: 'prdetails'
          mysql root password: 'root'
      - name: Run tests
        run: go test